### ISSUE TITLE
Suggestion for adding GreptimeDB example?

### ISSUE THREAD

**Issue by sunng87** [WasmEdge/wasmedge-db-examples#15]
I was trying to add an example for using mysql_async client to connect to GreptimeDB instance on cloud. Currently there are two blocking issues that I cannot just simply reuse the `crud.wasm` example:

- We require a timestamp index column in the table so the current `orders` table doesn't match, it results in a create table error
- In order to workaround a Grafana bug, we now set MySQL protocol TLS mode to `preferred`, while with mysql_async, it assumes server to be `required` https://github.com/blackbeam/mysql_async/issues/225#issuecomment-1409922237. So until Grafana has fixed their issue, we cannot use TLS in this example.

A simple proposal can be adding a new file and binary target in `mysql_async` module of this project, named as `greptimedb.rs`, as an example of connecting to greptimedb using wasmedge+mysql_async. Just to confirm if this will work for you.

**Comment by juntao** [comment]
I think we could even do a separate folder for greptimedb. You can see that all our examples are standalone -- they are not even in one workspace. 

The reason is that we want the user to copy a folder and just compile and use it. Say if the user want to use greptimedb, there is little chance that he will want the example to have Postgres dependency. In this aspect, the example of greptimedb and MySQL could be separate although they share the same driver.

We will also look into the TLS issue. Thanks!

**Comment by sunng87** [comment]
Sounds great! I will be working on a standalone greptimedb example and send PR when ready.
